# Generated by Django 5.0.4 on 2024-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='The',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=5000)),
                ('provenienza', models.CharField(max_length=80)),
                ('immagine', models.ImageField(upload_to='')),
            ],
        ),
    ]
