# Generated by Django 5.0.2 on 2024-04-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('commento', models.CharField(max_length=5000)),
                ('voto', models.IntegerField()),
                ('id_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the.the')),
                ('id_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the.the')),
                ('id_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the.user')),
            ],
        ),
    ]
